services:
  csprng:
    build: .
    image: csprng-img:latest
    container_name: csprng
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
